### ISSUE TITLE
[Historia] 

### ISSUE THREAD

**Issue by Yajayra18** [platzi/ella-se-educa-sola#2]
## Yajayra AF
* Nombre: Yajayra 
* Twitter: @yaja_af
* Historia: Hola Soy Yajayra Psicóloga de profesión y con mucha curiosidad por la tecnología, comencé aprendiendo programación gracias a mi enamorado, él me explicó las bases con el lenguaje de programación de Python, sinceramente me costó mucho mucho mucho entender las bases.

Me he frustrado muchas veces  y sé que me seguiré frustrando en el camino, sin embargo, miro hacia atrás y me siento muy agradecida de haber aprendido HTML, CSS, un poco de JavaScript, un poco de Python y ahora estoy aprendiendo las bases de C. 

Realicé mi perfil profesional en mobile y lo publiqué en twitter   [https://twitter.com/yaja_af/status/1346637815203901443](https://twitter.com/yaja_af/status/1346637815203901443)

Tengo  más aterrizada mis ideas de como ayudar a otros con tecnología, sin embargo estoy segura que será poco a poco y paso a paso. 

Gracias Platzi, ahora no tengo la suscripción, sin embargo aprovecho aplicar lo aprendido de grid a mi perfil profesional para mobile.

* Perfil de Platzi: Yajayra

**Comment by alexcamachogz** [comment]
Listo, ya puedes ver tu historia en el landing de ella se educa sola 🔥

**Comment by Yajayra18** [comment]
Gracias!
