### ISSUE TITLE
Diseñando mi futuro

### ISSUE THREAD

**Issue by chivagtz** [platzi/ella-se-educa-sola#3]
## Autora
* Nombre: Silvia Gutiérrez 
* Twitter: @chiva_gtz
* Historia: ¡Hola! Soy Silvia. Soy diseñadora gráfica y pronto, diseñadora web. Durante los 5 años de carrera, estaba interesada en la publicidad e incluso me desenvolví un poco en ello. Sin embargo, fue hace 3 años cuando, en la empresa que estaba laborando, me preguntaron si me interesaba cambiarme de área y apoyar con diseño web; yo, sin saber mucho, acepté y ahí es donde empezó el verdadero reto. Tuve que tomar cursos y aprender acerca del UX, ya que en la escuela ni lo habían mencionado (o no puse atención), me empeñé en entender HTML y CSS para entregar componentes y prototipos más entendibles para los desarrolladores; y poco a poco fui descubriendo **mi verdadera pasión**. Hoy, estoy a días de iniciar en una nueva empresa con el puesto de Web Designer, y no podría estar más orgullosa del camino recorrido, y emocionada por los nuevos rumbos por recorrer.
* Perfil de Platzi: https://platzi.com/p/silvia-gutierrez/

**Comment by alexcamachogz** [comment]
Listo, ya puedes ver tu historia en el landing de ella se educa sola 🔥
